language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi
